query AdminGetUserSingleVehicle($vehicleId: String!) {
  adminGetUserSingleVehicle(vehicleId: $vehicleId) {
    id
    status
    make
    model
    year
    mileage
    condition
    vin
    tav
    min
    max
    offer
    serviceHistory
    engineType
    transmission
    drivetrain
    structuralDamage
    mechanicalOverhaul
    userId
    agentName
    agentPhone
    scheduledAt
    expiresAt
    region
    imageUrls {
      imageUrl
      angle
    }
  }
}